# https://www.spigotmc.org/wiki/plugin-yml/
main: mlh.goofygoofies.minecraft_rp.MinecraftRP
name: MinecraftRP
version: 0.1.0

api-version: 1.16
depend: [SkinsRestorer]
authors: [Ali-Doggaz, eliboss, jkmartindale, kescardoso]
website: https://github.com/eliboss/minecraft_rp_mod

commands:

  claim:
    description: claim land 9 blocks at a time
  
  selfheal:
    description: heal up to 50 percent of your health if you are on claimed land
  
  unclaim:
    description: unclaim land owned by player who calls this command 9 blocks at a time

  jail:
    usage: /jail <Player Name> <Optional time in ms>
    description: puts a player in jail for n minutes

  inspect:
    usage: /inspect <Player Name>
    description: Checks if the player has any illegal items

  me:
    usage: Please describe your action. E.g '/me punches the developer'
    description: Describes the actions of the sender to nearby players

  it:
    usage: Please describe the event. E.g '/it The sky broke like an egg into full sunset, and the water caught fire.'
    description: Describes an event or a narrative.

  roll:
    usage: /roll generates a random number between 0 and 100, to determine how successful an action was.
    description: generates a random number between 100 and 0, to determine if an action has succeeded or not.

  ID:
    usage: /ID shows you ID card to players near you.
    description: Show your ID card to players near you (first and last name).

  heal:
    usage: /heal <Player Name>
    description: Completely heals a player.

  job:
    usage: /job <Job Name (Policeman, Doctor, or Judge)>
    description: Changes the player's job.

  transfer_money:
    usage: /transfer_money <Player Name> <Integer Amount>
    description: transfer some amount of money to another player

  check_land:
    description: for a player to check the land they own

  transfer_land:
    usage: /transfer_land <Player Name> <{List Coordinates}> <Integer Amount>

  transfer_itemFor$:
    usage: /transfer_itemFor$ <Player Name> <Material Item> <Integer Amount of Item> <Integer Amount of Gold>

  addShopItem:
    usage: /addShopItem <Material Item>  <Integer Amount of Item> <Integer Cost>

  removeShopItem:
    usage: /removeShopItem <Material Item>  <Integer Amount of Item> <Integer Cost>

  checkForItemToBuy:
    usage: /checkForItemToBuy <Material Item>

  checkMarketItems:
    description: check market for all items for sale

  sendMessageToSeller:
    usage: /sendMessageToSeller <Player sellerName> <Material item> <Integer amountOfItem>

  shop:
    description: open shop

  addGoldToPurse:
    usage: /addGoldToPurse <Integer amountToTransfer>
    description: add money to spend in the market

# permissions:
