# https://www.spigotmc.org/wiki/plugin-yml/

name: MinecraftRP
main: mlh.goofygoofies.minecraft_rp.MinecraftRP
version: 0.1.0

api-version: 1.16
authors: [Ali-Doggaz, eliboss, jkmartindale, kescardoso]
website: https://github.com/eliboss/minecraft_rp_mod

commands:
  jail:
    usage: /jail <Player Name> <Optional time in ms>
    description: puts a player in jail for n minutes

  me:
    usage: Please describe your action. E.g '/me punches the developer'
    description: Describes the actions of the sender to nearby players

  it:
    usage: Please describe the event. E.g '/it The sky broke like an egg into full sunset, and the water caught fire.'
    description: Describes an event or a narrative.

  roll:
    description: generates a random number between 100 and 0, to determine if an action has succeeded or not.

# permissions:
